name: Test & Release (if tagged)

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [10, 12, 14, 15]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: install & test
        run: |
          npm -v
          node -v
          npm i -g yarn
          yarn
          npm run bootstrap
          npm run build

          cd ./packages/api
          npm run test
        env:
          CI: true

  publish:
    name: Release
    uses: softprops/action-gh-release@v1
    if: startsWith(github.ref, 'refs/tags/')
    with:
      files: packages/cli/binaries/*
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
